# Generated by Django 4.1.7 on 2023-03-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ToUserName', models.CharField(max_length=100)),
                ('FromUserName', models.CharField(max_length=100)),
                ('CreateTime', models.CharField(max_length=100)),
                ('MsgType', models.CharField(max_length=100)),
                ('Content', models.CharField(max_length=1500)),
                ('MsgId', models.CharField(max_length=100)),
                ('MsgDataId', models.CharField(max_length=100)),
                ('Idx', models.CharField(max_length=100)),
            ],
        ),
    ]
